kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: web-deny-all
  namespace: application-service
spec:
  podSelector:
    matchLabels:
      control-plane: controller-manager
  ingress: []